apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  secret.json: |-
    {
      "api_key": "randomsecret"
    }


# We can also create secret using the file using the command 
# kubectl create secret generic mysecret --from-file .\from\file\secret.json
# Similar to a configMap object we will refer the secret to the pods/deployment using the volume and VolumeMounts